
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `Files`;
DROP TABLE IF EXISTS `Folders`;
DROP TABLE IF EXISTS `Groups`;
DROP TABLE IF EXISTS `User2Group`;
DROP TABLE IF EXISTS `UserGroups`;
DROP TABLE IF EXISTS `Users`;

SET FOREIGN_KEY_CHECKS = 1;